dist: xenial
arch: ppc64le
group: edge
script:
  - echo "Running Hello world (C program) using IBM advanced tool chain gcc compiler"
  - /opt/at12.0/bin/gcc hello_world.c -o hello_world_c_program
  - ./hello_world_c_program
  - echo "Running Hello world (C++ Program) using IBM advanced tool chain g++ compiler"
  - /opt/at12.0/bin/g++ hello_world.cpp -o hello_world_cpp_program
  - ./hello_world_cpp_program
  - echo "Running Hello world (GO Program) using IBM advanced tool chain gccgo compiler"
  - /opt/at12.0/bin/gccgo hello_world.go -o hello_world_go_program
  - ./hello_world_go_program
  - echo "Running Hello world (Nodejs Program)"
  - node hello_world.js
  - rm -rf hello_world_c_program hello_world_cpp_program hello_world_go_program
  - echo "Running Hello world (C program) using default gcc compiler"
  - gcc hello_world.c -o hello_world_c_program
  - ./hello_world_c_program
  - echo "Running Hello world (C++ Program) using default g++ compiler"
  - g++ hello_world.cpp -o hello_world_cpp_program
  - ./hello_world_cpp_program
  - echo "Running Hello world (GO Program) using default go"
  - cd /usr/local
